sudo: false

language: java

env:  
  global:
    - DISPLAY=:99.0

before_install:
  - sh -e /etc/init.d/xvfb start - sleep 10
  - mkdir surefire-reports/

jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

install: true

script:
- mvn clean verify

after_failure:
- ls surefire-reports/
- find surefire-reports -name '*.txt' -exec cat {} +
